services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: asd
      POSTGRES_PASSWORD: asd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
