apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ .Values.label.app }}
    component: {{ .Values.label.component }}
