apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label.app }}
    component: {{ .Values.label.component }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.label.app }}
      component: {{ .Values.label.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.label.app }}
        component: {{ .Values.label.component }}
      annotations:
        "helm.sh/revision": "{{ .Release.Revision }}"
    spec:
      containers:
      - name: spring
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy:   {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.port }}
