services:
  client:
    image: danchoivlado/blink-client
    ports:
      - "4173:4173"

  server:
    image: danchoivlado/blink-server
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres

  db:
    image: postgres
    environment:
      POSTGRES_USER: asd
      POSTGRES_PASSWORD: asd
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
