name: blink-message

services:
  client:
    image: danchoivlado/blink-client
    ports:
      - "4173:4173"

  server:
    image: danchoivlado/blink-server
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://database:5432/postgres
      - DB_PASSWORD=password

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
