apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.label.app }}
    component: {{ .Values.label.component }}
spec:
  ports:
    - port: {{ .Values.app.port}}
      targetPort: {{ .Values.app.port}}
  selector:
    app: {{ .Values.label.app }}
    component: {{ .Values.label.component }}
