apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label.app }}
    component: {{ .Values.label.component }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.label.app }}
      component: {{ .Values.label.component }}
  serviceName: {{ .Values.appName }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.label.app }}
        component: {{ .Values.label.component }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blink-message-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: {{ .Values.appName }}
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        namespace: {{ .Values.namespace }}
        name: {{ .Values.appName }}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: {{ .Values.storage }}
