apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label.app }}
    component: {{ .Values.label.component }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.label.app }}
      component: {{ .Values.label.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.label.app }}
        component: {{ .Values.label.component }}
    spec:
      containers:
      - name: spring
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_URL
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        - name: SERVER_PORT
          value: "8080"

        ports:
        - containerPort: {{ .Values.app.port }}
