apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label.app }}
    component: {{ .Values.label.component }}
spec:
  selector:
    app: {{ .Values.label.app }}
    component: {{ .Values.label.component }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
